### ISSUE TITLE
.to_cf not creating output

### ISSUE THREAD

**Issue by shaimona** [localytics/humidifier#44]
Quick read on your document page indicate stack.to_cf should output CF template. Is that correct? if it is, I used your example to create a CF template. instead of stack.deploy_and_wait I changed it to stack.to_cf expecting an output. but no output. Am I reading it wrong?

**Comment by kddeisz** [comment]
`stack.to_cf` returns a string that represents the output. What happens when you `puts stack.to_cf`?

**Comment by shaimona** [comment]
I was expecting stack.to_cf to output the template. puts stack.to_cf is displaying the template. I can redirect the output to a file but it would be nice if .to_cf can take an file name  argument and write the template out. I like to check-in templates to source control. just a suggestion

**Comment by kddeisz** [comment]
Thanks for the feedback! For now I would suggest doing something like `File.write('template.json', stack.to_cf)`.
